In [1]:
x=7*(3+8-4)/6
print(x)

8.166666666666666


In [2]:
5 and 6

6

In [2]:
days_of_week=['sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday']
days_of_week
              

['sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']

In [3]:
len(days_of_week)

7

In [4]:
 print(days_of_week[0])

sunday


In [5]:
print(days_of_week[4])

Thursday


In [7]:
my_list=[1,3,0,'true','so beautiful']
print(my_list)

[1, 3, 0, 'true', 'so beautiful']


In [16]:
age = 25
if age > 18:
    print("you can vote")
elif age < 18:
    print("you can't vote")
elif age == 18:
    print("get citizenship to vote")
else:
   print("invalid age")

you can vote


In [14]:
age = 25
if age > 18:
    print("You can vote")
elif age < 18:
    print("You can't vote")
elif age == 18:
    print("Get citizenship to vote")
else:
    print("Invalid age")

You can vote


In [21]:
X = 35
if X > 10 and X > 30:
    print("X is greater than 30.")
else:
    print("X is not greater than 30.")

X is greater than 30.


loop example

In [1]:
s="geeks"
for i in s:
    print(i)

g
e
e
k
s


python Dictionary eg

In [1]:
city_pop={
    "chicago":3.5,
    "New york":7,
    "LA":6
}
city_pop

{'chicago': 3.5, 'New york': 7, 'LA': 6}

In [3]:
city_pop={chicago}
    "chicago":3.5,
    "New york":7,
    "LA":6
}
city_pop

IndentationError: unexpected indent (1165567199.py, line 2)

In [4]:
city_pop.keys()

dict_keys(['chicago', 'New york', 'LA'])

In [5]:
city_pop.values()

dict_values([3.5, 7, 6])

In [6]:
"chicago"in city_pop

True

In [7]:
"San Franscisco"in city_pop

False

In [9]:
city_pop["LA"]=20
city_pop

{'chicago': 3.5, 'New york': 7, 'LA': 20}

In [10]:
city_pop.update({"chicago":30})
city_pop

{'chicago': 30, 'New york': 7, 'LA': 20}

add item dictionary eg

city_pop["kathmandu"]=2.5
city_pop

Remove item in dictionary

In [13]:
city_pop.pop("LA")
city_pop

{'chicago': 30, 'New york': 7, 'kathmandu': 2.5}

object-oriented concept

everything in python is an object.
Class and Object:
Class:class is like blue print for building object
Object:The instance of class called object

In [16]:
class student:
    school="school of Data science"

In [17]:
student1=student()
student2=student()
print(student1.school)
print(student2.school)

school of Data science
school of Data science


constructor in python:constructor is same as function

def_init_(self,name,level):
self.name=name
self.level=level these are the stntax of constructor 

NameError: name 'Student' is not defined

In [26]:
class Student:
    def __init__(self, name, level):
        self.name = name
        self.level = level


student1 = Student("kattle", 1)
student2 = Student("dipak", 3)

print(student1.name)  
print(student1.level) 
print(student2.name)  
print(student2.level)

kattle
1
dipak
3


In [2]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [3]:
pip install pandas


Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [1]:
pip instal matplotlib

Note: you may need to restart the kernel to use updated packages.


ERROR: unknown command "instal" - maybe you meant "install"



#Numpy library

In [2]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy
numpy.version

<module 'numpy.version' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\numpy\\version.py'>

In [6]:
import numpy as np
numpy.version

<module 'numpy.version' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\numpy\\version.py'>

In [19]:
my_arr=np.array([[2,4,8,16]],np.int32)
print(my_arr)
print(type(my_arr))
my_arr[0,1]

[[ 2  4  8 16]]
<class 'numpy.ndarray'>


4

In [20]:
my_arr.shape

(1, 4)

In [21]:
my_arr.dtype

dtype('int32')

##Arrays creation :Conversion from pther python structure

In [22]:
listarray=np.array([[1,2,3],[5,8,5],[0,3,1]])
print(listarray)

[[1 2 3]
 [5 8 5]
 [0 3 1]]


In [23]:
listarray.dtype

dtype('int32')

In [24]:
listarray.shape

(3, 3)

In [25]:
listarray.size

9

In [26]:
zeros=np.zeros([2,3])
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [33]:
rng=np.arange(20)
print(rng)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [35]:
lspace=np.linspace(1,5,12)
print(lspace)

[1.         1.36363636 1.72727273 2.09090909 2.45454545 2.81818182
 3.18181818 3.54545455 3.90909091 4.27272727 4.63636364 5.        ]


In [36]:
ide=np.identity(40)
print(ide)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
