In [1]:
x=7*(3+8-4)/6
print(x)

8.166666666666666


In [2]:
5 and 6

6

In [3]:
days_of_week=['sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday']
days_of_week
              

['sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']

In [4]:
len(days_of_week)

7

In [5]:
 print(days_of_week[0])

sunday


In [6]:
print(days_of_week[4])

Thursday


In [7]:
my_list=[1,3,0,'true','so beautiful']
print(my_list)

[1, 3, 0, 'true', 'so beautiful']


In [8]:
age = 25
if age > 18:
    print("you can vote")
elif age < 18:
    print("you can't vote")
elif age == 18:
    print("get citizenship to vote")
else:
   print("invalid age")

you can vote


In [9]:
age = 25
if age > 18:
    print("You can vote")
elif age < 18:
    print("You can't vote")
elif age == 18:
    print("Get citizenship to vote")
else:
    print("Invalid age")

You can vote


In [10]:
X = 35
if X > 10 and X > 30:
    print("X is greater than 30.")
else:
    print("X is not greater than 30.")

X is greater than 30.


loop example

In [11]:
s="geeks"
for i in s:
    print(i)

g
e
e
k
s


python Dictionary eg

In [12]:
city_pop={
    "chicago":3.5,
    "New york":7,
    "LA":6
}
city_pop

{'chicago': 3.5, 'New york': 7, 'LA': 6}

In [13]:
city_pop={chicago}
    "chicago":3.5,
    "New york":7,
    "LA":6
}
city_pop

IndentationError: unexpected indent (1165567199.py, line 2)

In [ ]:
city_pop.keys()

In [ ]:
city_pop.values()

In [ ]:
"chicago"in city_pop

In [ ]:
"San Franscisco"in city_pop

In [ ]:
city_pop["LA"]=20
city_pop

In [ ]:
city_pop.update({"chicago":30})
city_pop

add item dictionary eg

city_pop["kathmandu"]=2.5
city_pop

Remove item in dictionary

In [ ]:
city_pop.pop("LA")
city_pop

object-oriented concept

everything in python is an object.
Class and Object:
Class:class is like blue print for building object
Object:The instance of class called object

In [ ]:
class student:
    school="school of Data science"

In [ ]:
student1=student()
student2=student()
print(student1.school)
print(student2.school)

constructor in python:constructor is same as function

def_init_(self,name,level):
self.name=name
self.level=level these are the stntax of constructor 

In [ ]:
class Student:
    def __init__(self, name, level):
        self.name = name
        self.level = level


student1 = Student("kattle", 1)
student2 = Student("dipak", 3)

print(student1.name)  
print(student1.level) 
print(student2.name)  
print(student2.level)

In [ ]:
pip install numpy

In [ ]:
pip install pandas


In [ ]:
pip instal matplotlib

#Numpy library

In [1]:
pip install numpy


Defaulting to user installation because normal site-packages is not writeableNote: you may need to restart the kernel to use updated packages.



In [2]:
import numpy
numpy.version

<module 'numpy.version' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\numpy\\version.py'>

In [3]:
import numpy as np
numpy.version

<module 'numpy.version' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\numpy\\version.py'>

In [4]:
my_arr=np.array([[2,4,8,16]],np.int32)
print(my_arr)
print(type(my_arr))
my_arr[0,1]

[[ 2  4  8 16]]
<class 'numpy.ndarray'>


4

In [5]:
my_arr.shape

(1, 4)

In [6]:
my_arr.dtype

dtype('int32')

##Arrays creation :Conversion from pther python structure

In [7]:
listarray=np.array([[1,2,3],[5,8,5],[0,3,1]])
print(listarray)

[[1 2 3]
 [5 8 5]
 [0 3 1]]


In [8]:
listarray.dtype

dtype('int32')

In [9]:
listarray.shape

(3, 3)

In [10]:
listarray.size

9

In [11]:
zeros=np.zeros([2,3])
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [12]:
rng=np.arange(20)
print(rng)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [13]:
lspace=np.linspace(1,5,12)
print(lspace)

[1.         1.36363636 1.72727273 2.09090909 2.45454545 2.81818182
 3.18181818 3.54545455 3.90909091 4.27272727 4.63636364 5.        ]


In [14]:
ide=np.identity(40)
print(ide)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [15]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [16]:
import pandas

In [17]:
import pandas as pd
data = pd.Series([1, 2, 3, 4, 5])
print(data)


0    1
1    2
2    3
3    4
4    5
dtype: int64


In [18]:
import pandas as pd
data = pd.Series([0.25,0.5,0.75,1.0])
print(data)

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64


In [19]:
type(data)

pandas.core.series.Series

In [20]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [21]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [22]:
data[1:3]

1    0.50
2    0.75
dtype: float64

In [23]:
import pandas as pd
data=pd.Series([0.25,0.50,0.75,1.0],index=['a','b','c','d'])
print(data)

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64


In [24]:
data['c']


0.75

In [25]:
population_dict ={'California':38,
                  'Texas':26,
                  'New York':20,
                  'Florida':19,
                  'Illinois':13
                 }
population=pd.Series(population_dict)
print(population)

California    38
Texas         26
New York      20
Florida       19
Illinois      13
dtype: int64


In [ ]:
pd.Series ({2:'a',5:'b',3:'c'},index=[3,2])

In [26]:
area_dict={'California':423,
           'Texas':695,
           'Newyork':141,
           'Florida':170,
           'Illinois':150
          }
area=pd.Series(area_dict)
print(area)

California    423
Texas         695
Newyork       141
Florida       170
Illinois      150
dtype: int64


NaN Concept in Pandas

In [27]:
pd.DataFrame([{'a':2,'b':5},{'b':7,'c':1}])


a  b    c
0  2.0  5  NaN
1  NaN  7  1.0

In [28]:
'd' in data

True

In [29]:
data.keys

<bound method Series.keys of a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64>

In [30]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [34]:
data.loc[1:3]

TypeError: cannot do slice indexing on Index with these indexers [1] of type int

In [33]:
data.keys

<bound method Series.keys of a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64>

In [35]:
'd' in data

True

In [36]:
states=pd.DataFrame({'population':population,
                     'area':area})
print(states)

            population   area
California        38.0  423.0
Florida           19.0  170.0
Illinois          13.0  150.0
New York          20.0    NaN
Newyork            NaN  141.0
Texas             26.0  695.0


In [39]:
population['California']

38

In [40]:
type(states)

pandas.core.frame.DataFrame

In [41]:
states.index

Index(['California', 'Florida', 'Illinois', 'New York', 'Newyork', 'Texas'], dtype='object')

In [43]:
states.columns

Index(['population', 'area'], dtype='object')

In [46]:
states['area']

California    423.0
Florida       170.0
Illinois      150.0
New York        NaN
Newyork       141.0
Texas         695.0
Name: area, dtype: float64

In [47]:
states['population']

California    38.0
Florida       19.0
Illinois      13.0
New York      20.0
Newyork        NaN
Texas         26.0
Name: population, dtype: float64

In [48]:
population_dict={'Nepal':20000000,
                 'China':250000000,
                 'India':300000000}
population=pd.Series(population_dict)
print(population)

Nepal     20000000
China    250000000
India    300000000
dtype: int64


In [16]:
area_dict={'Nepal':12500,
           'China':35500,
           'India':550000}
area=pd.Series(area_dict)
print(area)

Nepal     12500
China     35500
India    550000
dtype: int64


In [7]:
import pandas as pd
country=pd.DataFrame({'population':population,
                      'area':area})
print(country)

NameError: name 'population' is not defined

In [2]:
states['density']=states['population']/states['area']
print(states)


NameError: name 'states' is not defined

In [3]:
import pandas as pd
data=pd.Series([0.25,0.5,0.75,1.0],index=['a','b','c','d'])
print(data)

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64


In [15]:
# Calculate density as population divided by area
states['density'] = states['population'] / states['area']

# Print the updated DataFrame
print(states)


        state  population    area     density
0  California    39538223  423967   93.257784
1       Texas    29145505  695662   41.896072
2     Florida    21538187  170312  126.463121
3    New York    20201249  141297  142.970120


In [3]:
import pandas as pd

# Sample DataFrame
states = pd.DataFrame({
    'state': ['California', 'Texas', 'Florida', 'New York'],
    'population': [39538223, 29145505, 21538187, 20201249],
    'area': [423967, 695662, 170312, 141297]  # in square kilometers
})

print(states)

        state  population    area
0  California    39538223  423967
1       Texas    29145505  695662
2     Florida    21538187  170312
3    New York    20201249  141297


In [4]:
states['density'] = states['population'] / states['area']

# Print the updated DataFrame
print(states)

        state  population    area     density
0  California    39538223  423967   93.257784
1       Texas    29145505  695662   41.896072
2     Florida    21538187  170312  126.463121
3    New York    20201249  141297  142.970120


In [12]:
import pandas as pd
city=pd.DataFrame({
    'city': ['Lahan','Brt','Ktm'],
    'population':[110000,510000,2000000],
    'area':[536,1000,30000]
})
print(city)


    city  population   area
0  Lahan      110000    536
1    Brt      510000   1000
2    Ktm     2000000  30000


In [9]:
city = pd.DataFrame({
    'city': ['Lahan', 'Brt', 'Ktm'],  # Added missing quotation mark
    'population': [110000, 510000, 2000000],
    'area': [536, 1000, 30000]
})
print(city)

    city  population   area
0  Lahan      110000    536
1    Brt      510000   1000
2    Ktm     2000000  30000


In [13]:
city['density']=city['population']/city['area']
print(city)

    city  population   area     density
0  Lahan      110000    536  205.223881
1    Brt      510000   1000  510.000000
2    Ktm     2000000  30000   66.666667


In [3]:
import pandas as pd
data=pd.DataFrame({
    'x':[78,85,96,80,86],
    'y':[84,94,89,83,80],
    'z':[86,97,96,72,83]
    })
print(data)

    x   y   z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  80  83


In [11]:
import pandas as pd
import numpy as np

data=pd.DataFrame({
    'name':['virat','dhoni','rohit','pant','rahul'],
    'score':[101,85,78,np.nan,56],
    'attempt':[1,1,2,2,1],
    'qualify':['yes','no','no','yes','yes'],
    'labels':['a','b','c','d','e']
})
print(data)

    name  score  attempt qualify labels
0  virat  101.0        1     yes      a
1  dhoni   85.0        1      no      b
2  rohit   78.0        2      no      c
3   pant    NaN        2     yes      d
4  rahul   56.0        1     yes      e


Assignment of Numpy

In [4]:
#Write Numpy program to create an array with the values 2,4,5,-2 and print the size of the memory occupied by the array?


import numpy as np
arr=np.array([2,4,5,-2])
print('array:',arr)
print('size of the memory array:',arr.nbytes,'bytes')

array: [ 2  4  5 -2]
size of the memory array: 16 bytes


In [2]:
import numpy as np
arr=np.array([2,4,5,-2])
print('array:',arr)
print('size of the memory array:',arr.nbytes,'bytes')

array: [ 2  4  5 -2]
size of the memory array: 16 bytes


In [9]:
#create a numpy array with 20 elements each of 0,1,2,3,4,5

import numpy as np
data=np.repeat([0,1,2,3,4,5],20)
print(data)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 5 5 5 5 5 5 5 5 5 5 5
 5 5 5 5 5 5 5 5 5]


In [11]:
#same problem in different method like

import numpy as np
data=[0,1,2,3,4,5]
repeat=20
data=np.tile(data,repeat)
print(data)

[0 1 2 3 4 5 0 1 2 3 4 5 0 1 2 3 4 5 0 1 2 3 4 5 0 1 2 3 4 5 0 1 2 3 4 5 0
 1 2 3 4 5 0 1 2 3 4 5 0 1 2 3 4 5 0 1 2 3 4 5 0 1 2 3 4 5 0 1 2 3 4 5 0 1
 2 3 4 5 0 1 2 3 4 5 0 1 2 3 4 5 0 1 2 3 4 5 0 1 2 3 4 5 0 1 2 3 4 5 0 1 2
 3 4 5 0 1 2 3 4 5]


In [15]:
#create numpy array of integers (3*4)arrays using arange() and reshap() in one line code

import numpy as np
arr=np.arange(12).reshape(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [1]:
# create a numpy program to create an array of 1000 random numbers from a normal distribution with mean of 10 and standard deviation of1.5?

import numpy as np
mean=10
std_dev=1.5
size=1000
random_numbers=np.random.normal(loc=mean,scale=std_dev,size=size)
print(random_numbers)


[11.35348813  9.79808662  9.44529888  8.75629761  9.72956252 10.11253461
  9.09507053 10.4611662   8.97387708 10.6329098   7.18408981  9.75504114
  9.25787813 10.23707405  8.02429886 10.72000714 12.1340703   9.01782371
 10.20454724  8.65408033 14.23993953 13.60869996  9.98493664  9.60823933
 10.71519011 11.48820615  9.93119799  9.63135808  9.07449401  9.65072209
 12.13188993  7.60805675 12.02714507  9.1034313  10.67024308 12.55527302
 10.54745376 10.6241894   8.05240769 12.51114581  8.13057182  9.64192847
 10.42370671  9.47953903 11.47698251  8.19250885  8.29550065 11.33360262
 10.66903853  8.12048728  9.78202685 11.51767368  9.71390302  8.80773117
 10.51904273  9.74978027  9.89923206  9.53526559 10.86627376  8.48610835
 10.25881326 12.50213927  7.80569633  8.9490915   9.89401976 11.66976473
 10.25392952  9.67733233 11.16471458  7.80116474  9.06065169 11.09353202
  8.70944957  9.18244215 12.47874407 12.84742581 12.10480419  7.97217928
 12.00814889  6.97507013  9.97785275 11.09199409  5